# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KoLDatabase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Charts', '~> 3.2.2'
  use_frameworks!

  # Pods for KoLDatabase

end
